export function getRandomMessage(): string {
	const messages: string[] = [
		'Halo! Apa kabar?',
		'Semangat terus, ya!',
		'Jangan lupa istirahat.',
		'Kamu hebat!',
		'Hari ini akan jadi hari yang baik.',
		'Tetap fokus dan jangan menyerah.',
		'Ingat, setiap usaha pasti ada hasil.',
		'Jaga kesehatan, ya!',
		'Terus belajar dan berkembang.',
		'Kamu tidak sendiri.',
		'Setiap tantangan adalah peluang.',
		'Kegagalan adalah bagian dari proses.',
		'Tersenyumlah, kamu luar biasa!',
		'Kamu mampu melalui ini.',
		'Ayo, jangan ragu mencoba hal baru!',
		'Hari ini kesempatan baru.',
		'Terima kasih sudah berusaha.',
		'Percayalah pada dirimu sendiri.',
		'Kesalahan adalah guru terbaik.',
		'Bersyukur atas hal-hal kecil.',
		'Kamu sudah sejauh ini, lanjutkan!',
		'Beri dirimu waktu untuk tumbuh.',
		'Satu langkah kecil tetap berarti.',
		'Kerja kerasmu tidak sia-sia.',
		'Tetap rendah hati dan terus melangkah.',
		'Jangan takut gagal, takut untuk tidak mencoba.',
		'Kamu pantas mendapatkan hal baik.',
		'Beristirahat juga bagian dari produktivitas.',
		'Teruslah mencoba, meskipun pelan.',
		'Setiap hari adalah awal yang baru.',
		'Kamu adalah inspirasi bagi orang lain.',
		'Tidak apa-apa untuk merasa lelah.',
		'Waktu akan menyembuhkan segalanya.',
		'Percaya prosesnya.',
		'Kamu lebih kuat dari yang kamu kira.',
		'Jangan bandingkan dirimu dengan orang lain.',
		'Lakukan yang terbaik versi dirimu.',
		'Tidak ada kata terlambat untuk memulai.',
		'Jangan lupakan mimpimu.',
		'Kamu layak untuk dicintai.',
		'Hari yang sulit bukan berarti hidup yang sulit.',
		'Setiap detik adalah kesempatan.',
		'Temukan keindahan dalam hal sederhana.',
		'Apa pun hasilnya, kamu sudah hebat.',
		'Kebaikan kecil bisa berdampak besar.',
		'Luangkan waktu untuk dirimu.',
		'Kamu bisa! Jangan menyerah.',
		'Apa yang kamu lakukan hari ini penting.',
		'Kamu sedang bertumbuh setiap hari.',
		'Jangan takut untuk menjadi dirimu sendiri.',
		'Percaya pada keajaiban usaha.',
		'Bahkan langkah kecil mendekatkan pada tujuan.',
		'Selalu ada harapan.',
		'Teruskan, kamu sedang dalam perjalananmu.',
		'Hidup ini penuh kejutan baik.',
		'Kamu tidak perlu sempurna untuk dicintai.',
		'Terus jadi versi terbaik dirimu.',
	]

	const index = Math.floor(Math.random() * messages.length)
	return messages[index]
}
